use_frameworks!

target 'YangLib_Example' do
  pod 'YangLib', :path => '../'

  target 'YangLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
